baseurl = "https://yonicd.netlify.com/"
DefaultContentLanguage = "en"
title = "Reproducible Random Thoughts"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
ignoreFiles = ["defaults$","\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disqusShortname = "yonicd"
googleAnalytics = "UA-84988961-2"
rssLimit = 20

[Params]
  subtitle = "Je T'aime Terminal"
  logo = "img/cd-icon.png"
  favicon = "img/cd-favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Jonathan Sidi"
  website = "yonicd.netlify.com"
  email = "yonicd@gmail.com"
  facebook = "yoniceedee"
  googleplus = "+yonicd"
  github = "yonicd"
  twitter = "yoniceedee"
  linkedin = "yonicd"

[[menu.main]]
    name = "Blog"
    url = ""

[[menu.main]]
    identifier = "R Packages"
    name = "R Packages"

[[menu.main]]
    parent = "R Packages"
    name = "Package Development"
    url = "page/packages/development/"

[[menu.main]]
    parent = "R Packages"
    name = "Reproducibility"
    url = "page/packages/reproducibility/"
    
[[menu.main]]
    parent = "R Packages"
    name = "Collaboration"
    url = "page/packages/collaborations/"    
    
[[menu.main]]
    parent = "R Packages"
    name = "Slack"
    url = "page/packages/slack/"

[[menu.main]]
    parent = "R Packages"
    name = "Utility"
    url = "page/packages/utility/"

[[menu.main]]
    parent = "R Packages"
    name = "Shiny"
    url = "page/packages/shiny/"

[[menu.main]]
    parent = "R Packages"
    name = "htmlwidgets"
    url = "page/packages/htmlwidgets/"
    
[[menu.main]]
    parent = "R Packages"
    name = "Statistics"
    url = "page/packages/statistics/"

[[menu.main]]
    name = "About"
    url = "page/about/"

[[menu.main]]
    identifier = "resources"
    name = "Resources"

[[menu.main]]
    parent = "resources"
    name = "R Weekly"
    url = "https://rweekly.org/"

[[menu.main]]
    parent = "resources"
    name = "R-bloggers"
    url = "http://www.r-bloggers.com"

[[menu.main]]
    parent = "resources"
    name = "ROpenSci"
    url = "https://ropensci.org/"

[[menu.main]]
    name = "Tags"
    url = "tags"
